title: Hype Annotation Guidelines
remote_theme: just-the-docs/just-the-docs

# Optional, but nice:
description: Annotation guidelines for hype-related adjectives in scientific writing
color_scheme: dark
