title: Hype Annotation Guidelines
url: "https://kansaineil.github.io"
baseurl: "/hype-annotation-guidelines-eacl26"
remote_theme: just-the-docs/just-the-docs

# Optional, but nice:
description: Annotation guidelines for hype-related adjectives in scientific writing
color_scheme: light
search_enabled: true
search:
  button: true
markdown: kramdown
